export type ShelterStatus = 'pending' | 'approved' | 'rejected' | 'suspended';

export class Shelter {
    private constructor(
        public readonly id: string,
        public readonly userOwnerId: string,
        public readonly name: string,
        public readonly description: string | null,
        public readonly phone: string | null,
        public readonly email: string | null,
        public readonly website: string | null,
        public readonly municipality: string | null,
        public readonly fullAddress: string | null,
        public readonly schedule: string | null,
        public readonly facebook: string | null,
        public readonly instagram: string | null,
        public readonly twitter: string | null,
        public readonly approved: boolean,
        public readonly status: ShelterStatus,
        public readonly logo: string | null,
        public readonly imageUrl: string | null,
        public readonly adoptionFee: number | null,
        public readonly createdAt: Date,
        public readonly updatedAt: Date,
        public readonly acceptsDonations: boolean,
        public readonly donationCauseText: string | null,
        public readonly donationClabe: string | null,
        public readonly donationBankName: string | null,
        public readonly donationAccountHolder: string | null,
        public readonly donationPaypalLink: string | null,
        public readonly donationMercadoPagoLink: string | null,
    ) { }

    public static create(shelterData: {
        id: string,
        userOwnerId: string,
        name: string,
        description: string | null,
        phone: string | null,
        email: string | null,
        website: string | null,
        municipality: string | null,
        fullAddress: string | null,
        schedule: string | null,
        facebook: string | null,
        instagram: string | null,
        twitter: string | null,
        approved: boolean,
        status: ShelterStatus,
        logo: string | null,
        imageUrl: string | null,
        adoptionFee: number | null,
        createdAt: Date,
        updatedAt: Date,
        acceptsDonations: boolean,
        donationCauseText: string | null,
        donationClabe: string | null,
        donationBankName: string | null,
        donationAccountHolder: string | null,
        donationPaypalLink: string | null,
        donationMercadoPagoLink: string | null,
    }): Shelter {
        return new Shelter(
            shelterData.id,
            shelterData.userOwnerId,
            shelterData.name,
            shelterData.description,
            shelterData.phone,
            shelterData.email,
            shelterData.website,
            shelterData.municipality,
            shelterData.fullAddress,
            shelterData.schedule,
            shelterData.facebook,
            shelterData.instagram,
            shelterData.twitter,
            shelterData.approved,
            shelterData.status,
            shelterData.logo,
            shelterData.imageUrl,
            shelterData.adoptionFee,
            shelterData.createdAt,
            shelterData.updatedAt,
            shelterData.acceptsDonations,
            shelterData.donationCauseText,
            shelterData.donationClabe,
            shelterData.donationBankName,
            shelterData.donationAccountHolder,
            shelterData.donationPaypalLink,
            shelterData.donationMercadoPagoLink,
        );
    }
}

export type ShelterFindAll = Pick<Shelter, "id" | "name" | "municipality" | "fullAddress" | "schedule" | "logo" | "imageUrl">;