export type ShelterStatus = 'pending' | 'approved' | 'rejected' | 'suspended';

export class Shelter {
    private constructor(
        public readonly id: string,
        public readonly userId: string,
        public readonly name: string,
        public readonly description: string | null,
        public readonly phone: string | null,
        public readonly email: string | null,
        public readonly website: string | null,
        public readonly ubicacion: string | null,
        public readonly ciudad: string | null,
        public readonly estado: string | null,
        public readonly facebook: string | null,
        public readonly instagram: string | null,
        public readonly twitter: string | null,
        public readonly aprobado: boolean,
        public readonly status: ShelterStatus,
        public readonly logo: string | null,
        public readonly imageUrl: string | null,
        public readonly createdAt: Date,
        public readonly updatedAt: Date,
    ) { }

    public static create(shelterData: {
        id: string,
        userId: string,
        name: string,
        description: string | null,
        phone: string | null,
        email: string | null,
        website: string | null,
        ubicacion: string | null,
        ciudad: string | null,
        estado: string | null,
        facebook: string | null,
        instagram: string | null,
        twitter: string | null,
        aprobado: boolean,
        status: ShelterStatus,
        logo: string | null,
        imageUrl: string | null,
        createdAt: Date,
        updatedAt: Date,
    }): Shelter {
        return new Shelter(
            shelterData.id,
            shelterData.userId,
            shelterData.name,
            shelterData.description,
            shelterData.phone,
            shelterData.email,
            shelterData.website,
            shelterData.ubicacion,
            shelterData.ciudad,
            shelterData.estado,
            shelterData.facebook,
            shelterData.instagram,
            shelterData.twitter,
            shelterData.aprobado,
            shelterData.status,
            shelterData.logo,
            shelterData.imageUrl,
            shelterData.createdAt,
            shelterData.updatedAt,
        );
    }
}